const seedRecipeData = {
    "meals": [
      {
        "idMeal": "53076",
        "strMeal": "Bread omelette",
        "strDrinkAlternate": null,
        "strCategory": "Breakfast",
        "strArea": "Indian",
        "strInstructions": "Make and enjoy",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/hqaejl1695738653.jpg",
        "strTags": null,
        "strYoutube": "",
        "strIngredient1": "Bread",
        "strIngredient2": "Egg",
        "strIngredient3": "Salt",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "2",
        "strMeasure2": "2",
        "strMeasure3": "0.5",
        "strMeasure4": " ",
        "strMeasure5": " ",
        "strMeasure6": " ",
        "strMeasure7": " ",
        "strMeasure8": " ",
        "strMeasure9": " ",
        "strMeasure10": " ",
        "strMeasure11": " ",
        "strMeasure12": " ",
        "strMeasure13": " ",
        "strMeasure14": " ",
        "strMeasure15": " ",
        "strMeasure16": " ",
        "strMeasure17": " ",
        "strMeasure18": " ",
        "strMeasure19": " ",
        "strMeasure20": " ",
        "strSource": "",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      },
      {
        "idMeal": "53036",
        "strMeal": "Boxty Breakfast",
        "strDrinkAlternate": null,
        "strCategory": "Pork",
        "strArea": "Irish",
        "strInstructions": "STEP 1\r\nBefore you start, put your oven on its lowest setting, ready to keep things warm. Peel the potatoes, grate 2 of them, then set aside. Cut the other 2 into large chunks, then boil for 10-15 mins or until tender. Meanwhile, squeeze as much of the liquid from the grated potatoes as you can using a clean tea towel. Mash the boiled potatoes, then mix with the grated potato, spring onions and flour.\r\n\r\nSTEP 2\r\nWhisk the egg white in a large bowl until it holds soft peaks. Fold in the buttermilk, then add the bicarbonate of soda. Fold into the potato mix.\r\n\r\nSTEP 3\r\nHeat a large non-stick frying pan over a medium heat, then add 1 tbsp butter and some of the oil. Drop 3-4 spoonfuls of the potato mixture into the pan, then gently cook for 3-5 mins on each side until golden and crusty. Keep warm on a plate in the oven while you cook the next batch, adding more butter and oil to the pan before you do so. You will get 16 crumpet-size boxty from the mix. Can be made the day ahead, drained on kitchen paper, then reheated in a low oven for 20 mins.\r\n\r\nSTEP 4\r\nHeat the grill to medium and put the tomatoes in a heavy-based pan. Add a good knob of butter and a little oil, then fry for about 5 mins until softened. Grill the bacon, then pile onto a plate and keep warm. Stack up the boxty, bacon and egg, and serve the tomatoes on the side.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/naqyel1608588563.jpg",
        "strTags": null,
        "strYoutube": "https://www.youtube.com/watch?v=80W0mCFDIP0",
        "strIngredient1": "Potatoes",
        "strIngredient2": "Spring Onions",
        "strIngredient3": "Plain Flour",
        "strIngredient4": "Egg White",
        "strIngredient5": "Milk",
        "strIngredient6": "Bicarbonate Of Soda",
        "strIngredient7": "Butter",
        "strIngredient8": "Vegetable Oil",
        "strIngredient9": "Cherry Tomatoes",
        "strIngredient10": "Bacon",
        "strIngredient11": "Egg",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "4 large",
        "strMeasure2": "1  bunch",
        "strMeasure3": "100g ",
        "strMeasure4": "1",
        "strMeasure5": "150ml",
        "strMeasure6": "1 tsp ",
        "strMeasure7": "3 tbs",
        "strMeasure8": "2 tbs",
        "strMeasure9": "6",
        "strMeasure10": "12",
        "strMeasure11": "6",
        "strMeasure12": " ",
        "strMeasure13": " ",
        "strMeasure14": " ",
        "strMeasure15": " ",
        "strMeasure16": " ",
        "strMeasure17": " ",
        "strMeasure18": " ",
        "strMeasure19": " ",
        "strMeasure20": " ",
        "strSource": "https://www.bbcgoodfood.com/recipes/boxty-bacon-eggs-tomatoes",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      },
      {
        "idMeal": "52895",
        "strMeal": "English Breakfast",
        "strDrinkAlternate": null,
        "strCategory": "Breakfast",
        "strArea": "British",
        "strInstructions": "Heat the flat grill plate over a low heat, on top of 2 rings/flames if it fits, and brush sparingly with light olive oil.\r\nCook the sausages first. Add the sausages to the hot grill plate/the coolest part if there is one and allow to cook slowly for about 15-20 minutes, turning occasionally, until golden. After the first 10 minutes, increase the heat to medium before beginning to cook the other ingredients. If you are struggling for space, completely cook the sausages and keep hot on a plate in the oven.\r\nSnip a few small cuts into the fatty edge of the bacon. Place the bacon straight on to the grill plate and fry for 2-4 minutes each side or until your preferred crispiness is reached. Like the sausages, the cooked bacon can be kept hot on a plate in the oven.\r\nFor the mushrooms, brush away any dirt using a pastry brush and trim the stalk level with the mushroom top. Season with salt and pepper and drizzle over a little olive oil. Place stalk-side up on the grill plate and cook for 1-2 minutes before turning and cooking for a further 3-4 minutes. Avoid moving the mushrooms too much while cooking, as this releases the natural juices, making them soggy.\r\nFor the tomatoes, cut the tomatoes across the centre/or in half lengthways if using plum tomatoes , and with a small, sharp knife remove the green 'eye'. Season with salt and pepper and drizzle with a little olive oil. Place cut-side down on the grill plate and cook without moving for 2 minutes. Gently turn over and season again. Cook for a further 2-3 minutes until tender but still holding their shape.\r\nFor the black pudding, cut the black pudding into 3-4 slices and remove the skin. Place on the grill plate and cook for 1½-2 minutes each side until slightly crispy.\r\nFor 'proper' fried bread it's best to cook it in a separate pan. Ideally, use bread that is a couple of days old. Heat a frying pan to a medium heat and cover the base with oil. Add the bread and cook for 2-3 minutes each side until crispy and golden. If the pan becomes too dry, add a little more oil. For a richer flavour, add a knob of butter after you turn the slice.\r\nFor the fried eggs, break the egg straight into the pan with the fried bread and leave for 30 seconds. Add a good knob of butter and lightly splash/baste the egg with the butter when melted. Cook to your preferred stage, season and gently remove with a fish slice.\r\nOnce all the ingredients are cooked, serve on warm plates and enjoy straight away with a good squeeze of tomato ketchup or brown sauce.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/utxryw1511721587.jpg",
        "strTags": "Breakfast",
        "strYoutube": "https://www.youtube.com/watch?v=FXjYU2Ensck",
        "strIngredient1": "Sausages",
        "strIngredient2": "Bacon",
        "strIngredient3": "Mushrooms",
        "strIngredient4": "Tomatoes",
        "strIngredient5": "Black Pudding",
        "strIngredient6": "Eggs",
        "strIngredient7": "Bread",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "2",
        "strMeasure2": "3",
        "strMeasure3": "2",
        "strMeasure4": "2",
        "strMeasure5": "1 Slice",
        "strMeasure6": "2",
        "strMeasure7": "1 Slice",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbc.co.uk/food/recipes/stressfreefullenglis_67721",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      },
      {
        "idMeal": "52940",
        "strMeal": "Brown Stew Chicken",
        "strDrinkAlternate": null,
        "strCategory": "Chicken",
        "strArea": "Jamaican",
        "strInstructions": "Squeeze lime over chicken and rub well. Drain off excess lime juice.\r\nCombine tomato, scallion, onion, garlic, pepper, thyme, pimento and soy sauce in a large bowl with the chicken pieces. Cover and marinate at least one hour.\r\nHeat oil in a dutch pot or large saucepan. Shake off the seasonings as you remove each piece of chicken from the marinade. Reserve the marinade for sauce.\r\nLightly brown the chicken a few pieces at a time in very hot oil. Place browned chicken pieces on a plate to rest while you brown the remaining pieces.\r\nDrain off excess oil and return the chicken to the pan. Pour the marinade over the chicken and add the carrots. Stir and cook over medium heat for 10 minutes.\r\nMix flour and coconut milk and add to stew, stirring constantly. Turn heat down to minimum and cook another 20 minutes or until tender.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/sypxpx1515365095.jpg",
        "strTags": "Stew",
        "strYoutube": "https://www.youtube.com/watch?v=_gFB1fkNhXs",
        "strIngredient1": "Chicken",
        "strIngredient2": "Tomato",
        "strIngredient3": "Onions",
        "strIngredient4": "Garlic Clove",
        "strIngredient5": "Red Pepper",
        "strIngredient6": "Carrots",
        "strIngredient7": "Lime",
        "strIngredient8": "Thyme",
        "strIngredient9": "Allspice",
        "strIngredient10": "Soy Sauce",
        "strIngredient11": "Cornstarch",
        "strIngredient12": "Coconut Milk",
        "strIngredient13": "Vegetable Oil",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "1 whole",
        "strMeasure2": "1 chopped",
        "strMeasure3": "2 chopped",
        "strMeasure4": "2 chopped",
        "strMeasure5": "1 chopped",
        "strMeasure6": "1 chopped",
        "strMeasure7": "1",
        "strMeasure8": "2 tsp",
        "strMeasure9": "1 tsp ",
        "strMeasure10": "2 tbs",
        "strMeasure11": "2 tsp",
        "strMeasure12": "2 cups ",
        "strMeasure13": "1 tbs",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "http://www.geniuskitchen.com/recipe/authentic-jamaican-brown-stew-chicken-347996",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      },
      {
        "idMeal": "52965",
        "strMeal": "Breakfast Potatoes",
        "strDrinkAlternate": null,
        "strCategory": "Breakfast",
        "strArea": "Canadian",
        "strInstructions": "Before you do anything, freeze your bacon slices that way when you're ready to prep, it'll be so much easier to chop!\r\nWash the potatoes and cut medium dice into square pieces. To prevent any browning, place the already cut potatoes in a bowl filled with water.\r\nIn the meantime, heat 1-2 tablespoons of oil in a large skillet over medium-high heat. Tilt the skillet so the oil spreads evenly.\r\nOnce the oil is hot, drain the potatoes and add to the skillet. Season with salt, pepper, and Old Bay as needed.\r\nCook for 10 minutes, stirring the potatoes often, until brown. If needed, add a tablespoon more of oil.\r\nChop up the bacon and add to the potatoes. The bacon will start to render and the fat will begin to further cook the potatoes. Toss it up a bit! The bacon will take 5-6 minutes to crisp.\r\nOnce the bacon is cooked, reduce the heat to medium-low, add the minced garlic and toss. Season once more. Add dried or fresh parsley. Control heat as needed.\r\nLet the garlic cook until fragrant, about one minute.\r\nJust before serving, drizzle over the maple syrup and toss. Let that cook another minute, giving the potatoes a caramelized effect.\r\nServe in a warm bowl with a sunny side up egg!",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/1550441882.jpg",
        "strTags": "Breakfast,Brunch,",
        "strYoutube": "https://www.youtube.com/watch?v=BoD0TIO9nE4",
        "strIngredient1": "Potatoes",
        "strIngredient2": "Olive Oil",
        "strIngredient3": "Bacon",
        "strIngredient4": "Garlic Clove",
        "strIngredient5": "Maple Syrup",
        "strIngredient6": "Parsley",
        "strIngredient7": "Salt",
        "strIngredient8": "Pepper",
        "strIngredient9": "Allspice",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "3 Medium",
        "strMeasure2": "1 tbs",
        "strMeasure3": "2 strips",
        "strMeasure4": "Minced",
        "strMeasure5": "1 tbs",
        "strMeasure6": "Garnish",
        "strMeasure7": "Pinch",
        "strMeasure8": "Pinch",
        "strMeasure9": "To taste",
        "strMeasure10": " ",
        "strMeasure11": " ",
        "strMeasure12": " ",
        "strMeasure13": " ",
        "strMeasure14": " ",
        "strMeasure15": " ",
        "strMeasure16": " ",
        "strMeasure17": " ",
        "strMeasure18": " ",
        "strMeasure19": " ",
        "strMeasure20": " ",
        "strSource": "http://www.vodkaandbiscuits.com/2014/03/06/bangin-breakfast-potatoes/",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      },
      {
        "idMeal": "52975",
        "strMeal": "Tuna and Egg Briks",
        "strDrinkAlternate": null,
        "strCategory": "Seafood",
        "strArea": "Tunisian",
        "strInstructions": "Heat 2 tsp of the oil in a large saucepan and cook the spring onions over a low heat for 3 minutes or until beginning to soften. Add the spinach, cover with a tight-fitting lid and cook for a further 2–3 minutes or until tender and wilted, stirring once or twice. Tip the mixture into a sieve or colander and leave to drain and cool.\r\nUsing a saucer as a guide, cut out 24 rounds about 12.5 cm (5 in) in diameter from the filo pastry, cutting 6 rounds from each sheet. Stack the filo rounds in a pile, then cover with cling film to prevent them from drying out.\r\nWhen the spinach mixture is cool, squeeze out as much excess liquid as possible, then transfer to a bowl. Add the tuna, eggs, hot pepper sauce, and salt and pepper to taste. Mix well.\r\nPreheat the oven to 200°C (400°F, gas mark 6). Take one filo round and very lightly brush with some of the remaining oil. Top with a second round and brush with a little oil, then place a third round on top and brush with oil.\r\nPlace a heaped tbsp of the filling in the middle of the round, then fold the pastry over to make a half-moon shape. Fold in the edges, twisting them to seal, and place on a non-stick baking sheet. Repeat with the remaining pastry and filling to make 8 briks in all.\r\nLightly brush the briks with the remaining oil. Bake for 12–15 minutes or until the pastry is crisp and golden brown.\r\nMeanwhile, combine the tomatoes and cucumber in a bowl and sprinkle with the lemon juice and seasoning to taste. Serve the briks hot with this salad and the chutney.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/2dsltq1560461468.jpg",
        "strTags": null,
        "strYoutube": "https://www.youtube.com/watch?v=C5n1fN8TGHs",
        "strIngredient1": "Olive Oil",
        "strIngredient2": "Spring Onions",
        "strIngredient3": "Spinach",
        "strIngredient4": "Filo Pastry",
        "strIngredient5": "Tuna",
        "strIngredient6": "Eggs",
        "strIngredient7": "Hotsauce",
        "strIngredient8": "Tomatoes",
        "strIngredient9": "Cucumber",
        "strIngredient10": "Lemon Juice",
        "strIngredient11": "Apricot Jam",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "2 tbs",
        "strMeasure2": "8",
        "strMeasure3": "200g",
        "strMeasure4": "4",
        "strMeasure5": "1 can ",
        "strMeasure6": "2",
        "strMeasure7": "Dash",
        "strMeasure8": "4 Chopped",
        "strMeasure9": "1/4 ",
        "strMeasure10": "1 tbs",
        "strMeasure11": "4 tbs",
        "strMeasure12": " ",
        "strMeasure13": " ",
        "strMeasure14": " ",
        "strMeasure15": " ",
        "strMeasure16": " ",
        "strMeasure17": " ",
        "strMeasure18": " ",
        "strMeasure19": " ",
        "strMeasure20": " ",
        "strSource": "http://allrecipes.co.uk/recipe/3096/tunisian-tuna-and-egg-briks.aspx",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      },
      {
        "idMeal": "52826",
        "strMeal": "Braised Beef Chilli",
        "strDrinkAlternate": null,
        "strCategory": "Beef",
        "strArea": "Mexican",
        "strInstructions": "Preheat the oven to 120C/225F/gas mark 1.\r\n\r\nTake the meat out of the fridge to de-chill. Pulse the onions and garlic in a food processor until finely chopped. Heat 2 tbsp olive oil in a large casserole and sear the meat on all sides until golden.\r\n\r\nSet to one side and add another small slug of oil to brown the chorizo. Remove and add the onion and garlic, spices, herbs and chillies then cook until soft in the chorizo oil. Season with salt and pepper and add the vinegar, tomatoes, ketchup and sugar.\r\n\r\nPut all the meat back into the pot with 400ml water (or red wine if you prefer), bring up to a simmer and cook, covered, in the low oven.\r\n\r\nAfter 2 hours, check the meat and add the beans. Cook for a further hour and just before serving, pull the meat apart with a pair of forks.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/uuqvwu1504629254.jpg",
        "strTags": null,
        "strYoutube": "https://www.youtube.com/watch?v=z4kSoJgsu6Y",
        "strIngredient1": "Beef",
        "strIngredient2": "Onions",
        "strIngredient3": "Garlic",
        "strIngredient4": "Olive oil",
        "strIngredient5": "Chorizo",
        "strIngredient6": "Cumin",
        "strIngredient7": "All spice",
        "strIngredient8": "Cloves",
        "strIngredient9": "Cinnamon stick",
        "strIngredient10": "Bay Leaves",
        "strIngredient11": "Oregano",
        "strIngredient12": "Ancho Chillies",
        "strIngredient13": "Balsamic Vinegar",
        "strIngredient14": "Plum Tomatoes",
        "strIngredient15": "Tomato Ketchup",
        "strIngredient16": "Dark Brown Sugar",
        "strIngredient17": "Borlotti Beans",
        "strIngredient18": null,
        "strIngredient19": null,
        "strIngredient20": null,
        "strMeasure1": "1kg",
        "strMeasure2": "3",
        "strMeasure3": "4 cloves",
        "strMeasure4": "Dash",
        "strMeasure5": "300g",
        "strMeasure6": "2 tsp",
        "strMeasure7": "2 tsp",
        "strMeasure8": "1 tsp",
        "strMeasure9": "1 large",
        "strMeasure10": "3",
        "strMeasure11": "2 tsp dried",
        "strMeasure12": "2 ancho",
        "strMeasure13": "3 tbsp",
        "strMeasure14": "2 x 400g",
        "strMeasure15": "2 tbsp",
        "strMeasure16": "2 tbsp",
        "strMeasure17": "2 x 400g tins",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "http://www.telegraph.co.uk/food-and-drink/recipes/braised-beef-chilli-con-carne/",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      },
      {
        "idMeal": "52812",
        "strMeal": "Beef Brisket Pot Roast",
        "strDrinkAlternate": null,
        "strCategory": "Beef",
        "strArea": "American",
        "strInstructions": "1 Prepare the brisket for cooking: On one side of the brisket there should be a layer of fat, which you want. If there are any large chunks of fat, cut them off and discard them. Large pieces of fat will not be able to render out completely.\r\nUsing a sharp knife, score the fat in parallel lines, about 3/4-inch apart. Slice through the fat, not the beef. Repeat in the opposite direction to make a cross-hatch pattern.\r\nSalt the brisket well and let it sit at room temperature for 30 minutes.\r\n \r\n2 Sear the brisket: You'll need an oven-proof, thick-bottomed pot with a cover, or Dutch oven, that is just wide enough to hold the brisket roast with a little room for the onions.\r\nPat the brisket dry and place it, fatty side down, into the pot and place it on medium high heat. Cook for 5-8 minutes, lightly sizzling, until the fat side is nicely browned. (If the roast seems to be cooking too fast, turn the heat down to medium. You want a steady sizzle, not a raging sear.)\r\nTurn the brisket over and cook for a few minutes more to brown the other side.\r\n\r\n3 Sauté the onions and garlic: When the brisket has browned, remove it from the pot and set aside. There should be a couple tablespoons of fat rendered in the pot, if not, add some olive oil.\r\nAdd the chopped onions and increase the heat to high. Sprinkle a little salt on the onions. Sauté, stirring often, until the onions are lightly browned, 5-8 minutes. Stir in the garlic and cook 1-2 more minutes.\r\n \r\n4 Return brisket to pot, add herbs, stock, bring to simmer, cover, cook in oven: Preheat the oven to 300°F. Use kitchen twine to tie together the bay leaves, rosemary and thyme.\r\nMove the onions and garlic to the sides of the pot and nestle the brisket inside. Add the beef stock and the tied-up herbs. Bring the stock to a boil on the stovetop.\r\nCover the pot, place the pot in the 300°F oven and cook for 3 hours. Carefully flip the brisket every hour so it cooks evenly.\r\n \r\n5 Add carrots, continue to cook: After 3 hours, add the carrots. Cover the pot and cook for 1 hour more, or until the carrots are cooked through and the brisket is falling-apart tender.\r\n6 Remove brisket to cutting board, tent with foil: When the brisket is falling-apart tender, take the pot out of the oven and remove the brisket to a cutting board. Cover it with foil. Pull out and discard the herbs.\r\n7 Make sauce (optional): At this point you have two options. You can serve as is, or you can make a sauce with the drippings and some of the onions. If you serve as is, skip this step.\r\nTo make a sauce, remove the carrots and half of the onions, set aside and cover them with foil. Pour the ingredients that are remaining into the pot into a blender, and purée until smooth. If you want, add 1 tablespoon of mustard to the mix. Put into a small pot and keep warm.\r\n8 Slice the meat across the grain: Notice the lines of the muscle fibers of the roast. This is the \"grain\" of the meat. Slice the meat perpendicular to these lines, or across the grain (cutting this way further tenderizes the meat), in 1/4-inch to 1/2-inch slices.\r\nServe with the onions, carrots and gravy. Serve with mashed, roasted or boiled potatoes, egg noodles or polenta.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/ursuup1487348423.jpg",
        "strTags": "Meat",
        "strYoutube": "https://www.youtube.com/watch?v=gh48wM6bPWQ",
        "strIngredient1": "Beef Brisket",
        "strIngredient2": "Salt",
        "strIngredient3": "Onion",
        "strIngredient4": "Garlic",
        "strIngredient5": "Thyme",
        "strIngredient6": "Rosemary",
        "strIngredient7": "Bay Leaves",
        "strIngredient8": "beef stock",
        "strIngredient9": "Carrots",
        "strIngredient10": "Mustard",
        "strIngredient11": "Potatoes",
        "strIngredient12": null,
        "strIngredient13": null,
        "strIngredient14": null,
        "strIngredient15": null,
        "strIngredient16": null,
        "strIngredient17": null,
        "strIngredient18": null,
        "strIngredient19": null,
        "strIngredient20": null,
        "strMeasure1": "4-5 pound",
        "strMeasure2": "Dash",
        "strMeasure3": "3",
        "strMeasure4": "5 cloves",
        "strMeasure5": "1 Sprig",
        "strMeasure6": "1 sprig ",
        "strMeasure7": "4",
        "strMeasure8": "2 cups",
        "strMeasure9": "3 Large",
        "strMeasure10": "1 Tbsp",
        "strMeasure11": "4 Mashed",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "http://www.simplyrecipes.com/recipes/beef_brisket_pot_roast/",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      }
    ]
  }

export default seedRecipeData